POST http://localhost:8080/signup
Content-Type: application/json

{
   "name": "carlos",
   "email": "carlos.olivera.7e6@itb.cat",
   "password": "carlospasssword"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
"email": "carlos.olivera.7e6@itb.cat",
"password": "carlospasssword"
}

###
POST http://192.168.1.68:8080/posts
Content-Type: application/json

{
"tittle": "Perro con pulgas",
"owner": 0,
"reciver": 1,
"offers":  "Ninguna" ,
"postPhoto": "https://acortar.link/TYEvTw",
"description": "Que alguien me bañe al perro",
"serviceType": "Peluqueria",
"serviceTime": "08:00 - 10:00",
"postDate": "2024-02-16",
"reward": "100€",
"location": "Barcelona"
}

###
GET http://192.168.1.68:8080/posts

###
PUT http://192.168.1.68:8080/posts/3
Content-Type: application/json

{
  "tittle": "Gato",
  "owner": 0,
  "reciver": 1,
  "offers":  "14" ,
  "postPhoto": "https://acortar.link/g7gi5i",
  "description": "Que alguien me cuide al gato",
  "serviceType": "Paseo",
  "serviceTime": "00:00 - 10:00",
  "postDate": "2024-02-16",
  "reward": "1000€",
  "location": "Barcelona"
}

###
DELETE http://192.168.1.68:8080/posts/7
Content-Type: application/json

###
DELETE http://192.168.1.68:8080/posts/12
Content-Type: application/json
###
DELETE http://192.168.1.68:8080/posts/16
Content-Type: application/json
###
DELETE http://192.168.1.68:8080/posts/15
Content-Type: application/json


